name: Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yml

  upload-to-pypi:
    name: Upload to PyPI
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -U uv

      - name: Download wheel from build-and-test
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Upload to PyPI
        run: |
          uv publish
